export default [
  { id: 1, name: "fashion" },
  { id: 2, name: "beauty" },
  { id: 3, name: "travel" },
  { id: 4, name: "lifestyle" },
  { id: 5, name: "personal" },
  { id: 6, name: "tech" },
  { id: 7, name: "health" },
  { id: 8, name: "business" },
  { id: 9, name: "education" },
  { id: 10, name: "food" },
  { id: 11, name: "music" },
  { id: 12, name: "coding" },
  { id: 14, name: "marketing" },
  { id: 15, name: "art" },
  { id: 16, name: "agriculture" },
  { id: 17, name: "gaming" },
  { id: 18, name: "history" },
  { id: 19, name: "news" },
  { id: 20, name: "photography" },
];
